name: release

on:
  push:
    tags:
      - v*

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ['3.7.1', '3.8', '3.9', '3.10', '3.11', '3.12', 'pypy-3.9']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - run: |
        make test

  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: build
      run: |
        ./run.sh build
    - name: check
      run: |
        ./run.sh check
    - name: release
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_DEPLOY_TOKEN }}
